//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloBDContainer : DbContext
    {
        public ModeloBDContainer()
            : base("name=ModeloBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amistad> Amistad { get; set; }
        public virtual DbSet<Baneo> Baneo { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<recuperarContrasenia> recuperarContrasenia { get; set; }
        public virtual DbSet<jugadorPartida> jugadorPartida { get; set; }
    }
}
