//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador
{
    using System;
    using System.Collections.Generic;
    
    public partial class recuperarContrasenia
    {
        public int idRecuperacionContrasenia { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaExpiracion { get; set; }
        public int idCuenta { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
