//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador.Servidor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugadorr", Namespace="http://schemas.datacontract.org/2004/07/trofeoDelCazadorServicio.Servicios.gestio" +
        "nUsuario")]
    [System.SerializableAttribute()]
    public partial class Jugadorr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> partidasGanadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> partidasJugadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((this.fechaRegistroField.Equals(value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("fechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCuenta {
            get {
                return this.idCuentaField;
            }
            set {
                if ((this.idCuentaField.Equals(value) != true)) {
                    this.idCuentaField = value;
                    this.RaisePropertyChanged("idCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> partidasGanadas {
            get {
                return this.partidasGanadasField;
            }
            set {
                if ((this.partidasGanadasField.Equals(value) != true)) {
                    this.partidasGanadasField = value;
                    this.RaisePropertyChanged("partidasGanadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> partidasJugadas {
            get {
                return this.partidasJugadasField;
            }
            set {
                if ((this.partidasJugadasField.Equals(value) != true)) {
                    this.partidasJugadasField = value;
                    this.RaisePropertyChanged("partidasJugadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionUsuario")]
    public interface IGestionUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuario/agregarJugador", ReplyAction="http://tempuri.org/IGestionUsuario/agregarJugadorResponse")]
        int agregarJugador(trofeoCazador.Servidor.Jugadorr jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuario/agregarJugador", ReplyAction="http://tempuri.org/IGestionUsuario/agregarJugadorResponse")]
        System.Threading.Tasks.Task<int> agregarJugadorAsync(trofeoCazador.Servidor.Jugadorr jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuario/obtenerJugador", ReplyAction="http://tempuri.org/IGestionUsuario/obtenerJugadorResponse")]
        trofeoCazador.Servidor.Jugadorr obtenerJugador(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionUsuario/obtenerJugador", ReplyAction="http://tempuri.org/IGestionUsuario/obtenerJugadorResponse")]
        System.Threading.Tasks.Task<trofeoCazador.Servidor.Jugadorr> obtenerJugadorAsync(int idJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionUsuarioChannel : trofeoCazador.Servidor.IGestionUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionUsuarioClient : System.ServiceModel.ClientBase<trofeoCazador.Servidor.IGestionUsuario>, trofeoCazador.Servidor.IGestionUsuario {
        
        public GestionUsuarioClient() {
        }
        
        public GestionUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int agregarJugador(trofeoCazador.Servidor.Jugadorr jugador) {
            return base.Channel.agregarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<int> agregarJugadorAsync(trofeoCazador.Servidor.Jugadorr jugador) {
            return base.Channel.agregarJugadorAsync(jugador);
        }
        
        public trofeoCazador.Servidor.Jugadorr obtenerJugador(int idJugador) {
            return base.Channel.obtenerJugador(idJugador);
        }
        
        public System.Threading.Tasks.Task<trofeoCazador.Servidor.Jugadorr> obtenerJugadorAsync(int idJugador) {
            return base.Channel.obtenerJugadorAsync(idJugador);
        }
    }
}
