//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trofeoCazador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvide mi contraseña .
        /// </summary>
        public static string btnForgotPassword_ {
            get {
                return ResourceManager.GetString("btnForgotPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión .
        /// </summary>
        public static string btnLogin_ {
            get {
                return ResourceManager.GetString("btnLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse .
        /// </summary>
        public static string btnRegister_ {
            get {
                return ResourceManager.GetString("btnRegister ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitado .
        /// </summary>
        public static string Guest_ {
            get {
                return ResourceManager.GetString("Guest ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALORNORMAL.
        /// </summary>
        public static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión .
        /// </summary>
        public static string lbLogin_ {
            get {
                return ResourceManager.GetString("lbLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña .
        /// </summary>
        public static string lbPassword_ {
            get {
                return ResourceManager.GetString("lbPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario .
        /// </summary>
        public static string lbUserName_ {
            get {
                return ResourceManager.GetString("lbUserName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha dejado campos vacios, complete todos .
        /// </summary>
        public static string lbWLogin_ {
            get {
                return ResourceManager.GetString("lbWLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados son incorrectos, intente de nuevo .
        /// </summary>
        public static string lbWLoginWrongData {
            get {
                return ResourceManager.GetString("lbWLoginWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Nuevo? .
        /// </summary>
        public static string NewInGame_ {
            get {
                return ResourceManager.GetString("NewInGame ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter´s Tropy .
        /// </summary>
        public static string TitleGame_ {
            get {
                return ResourceManager.GetString("TitleGame ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión .
        /// </summary>
        public static string vtLogin {
            get {
                return ResourceManager.GetString("vtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia .
        /// </summary>
        public static string vtWarningLogin_ {
            get {
                return ResourceManager.GetString("vtWarningLogin ", resourceCulture);
            }
        }
    }
}
