//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trofeoCazador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string btnCreateAccount {
            get {
                return ResourceManager.GetString("btnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        public static string btnGlobalBack {
            get {
                return ResourceManager.GetString("btnGlobalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnGlobalCancel {
            get {
                return ResourceManager.GetString("btnGlobalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnGlobalSave {
            get {
                return ResourceManager.GetString("btnGlobalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string btnLogin_ {
            get {
                return ResourceManager.GetString("btnLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar nuevo código.
        /// </summary>
        public static string btnRequestNewCode {
            get {
                return ResourceManager.GetString("btnRequestNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código.
        /// </summary>
        public static string btnSendCode {
            get {
                return ResourceManager.GetString("btnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidaste tu contraseña.
        /// </summary>
        public static string forgotPassword_ {
            get {
                return ResourceManager.GetString("forgotPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado .
        /// </summary>
        public static string Guest_ {
            get {
                return ResourceManager.GetString("Guest ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALORNORMAL.
        /// </summary>
        public static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 12 caracteres.
        /// </summary>
        public static string lbAtLeast12Characters {
            get {
                return ResourceManager.GetString("lbAtLeast12Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un numero.
        /// </summary>
        public static string lbAtLeastOneNumber {
            get {
                return ResourceManager.GetString("lbAtLeastOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string lbCreateAccount {
            get {
                return ResourceManager.GetString("lbCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu cuenta.
        /// </summary>
        public static string lbCreateYourAccount {
            get {
                return ResourceManager.GetString("lbCreateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo actual.
        /// </summary>
        public static string lbCurrentEmail {
            get {
                return ResourceManager.GetString("lbCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre actual.
        /// </summary>
        public static string lbCurrentName {
            get {
                return ResourceManager.GetString("lbCurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena actual.
        /// </summary>
        public static string lbCurrentPassword {
            get {
                return ResourceManager.GetString("lbCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario actual.
        /// </summary>
        public static string lbCurrentUsername {
            get {
                return ResourceManager.GetString("lbCurrentUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string lbDateOfTheBird_ {
            get {
                return ResourceManager.GetString("lbDateOfTheBird ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string lbEmail_ {
            get {
                return ResourceManager.GetString("lbEmail ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código que se le envio a su correo.
        /// </summary>
        public static string lbEnterVerificationCode {
            get {
                return ResourceManager.GetString("lbEnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvide mi contraseña .
        /// </summary>
        public static string lbForgotPassword_ {
            get {
                return ResourceManager.GetString("lbForgotPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer apellido.
        /// </summary>
        public static string lbGlobalFirstLastName_ {
            get {
                return ResourceManager.GetString("lbGlobalFirstLastName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo apellido.
        /// </summary>
        public static string lbGlobalFirstSecondLastName_ {
            get {
                return ResourceManager.GetString("lbGlobalFirstSecondLastName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lbGlobalName_ {
            get {
                return ResourceManager.GetString("lbGlobalName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbGlobalPassword_ {
            get {
                return ResourceManager.GetString("lbGlobalPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string lbGlobalUsername_ {
            get {
                return ResourceManager.GetString("lbGlobalUsername ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa los siguientes datos.
        /// </summary>
        public static string lbInsertData {
            get {
                return ResourceManager.GetString("lbInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string lbLogin_ {
            get {
                return ResourceManager.GetString("lbLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una minúscula .
        /// </summary>
        public static string lbLowercaseLetterRequirement_ {
            get {
                return ResourceManager.GetString("lbLowercaseLetterRequirement ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes llenar los campos obligatorios.
        /// </summary>
        public static string lbMustFillFields {
            get {
                return ResourceManager.GetString("lbMustFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo correo.
        /// </summary>
        public static string lbNewEmail {
            get {
                return ResourceManager.GetString("lbNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo apellido.
        /// </summary>
        public static string lbNewLastName {
            get {
                return ResourceManager.GetString("lbNewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre.
        /// </summary>
        public static string lbNewName {
            get {
                return ResourceManager.GetString("lbNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contrasena.
        /// </summary>
        public static string lbNewPassword {
            get {
                return ResourceManager.GetString("lbNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre de usuario.
        /// </summary>
        public static string lbNewUsername {
            get {
                return ResourceManager.GetString("lbNewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña .
        /// </summary>
        public static string lbPassword_ {
            get {
                return ResourceManager.GetString("lbPassword ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener.
        /// </summary>
        public static string lbPasswordPolitic {
            get {
                return ResourceManager.GetString("lbPasswordPolitic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse .
        /// </summary>
        public static string lbRegister_ {
            get {
                return ResourceManager.GetString("lbRegister ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por le menos un caracter especial.
        /// </summary>
        public static string lbSpecialCharacterRequirement_ {
            get {
                return ResourceManager.GetString("lbSpecialCharacterRequirement ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar correo.
        /// </summary>
        public static string lbTitleChangeEmail {
            get {
                return ResourceManager.GetString("lbTitleChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string lbTitleChangePassword {
            get {
                return ResourceManager.GetString("lbTitleChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre.
        /// </summary>
        public static string lbTitleEditName {
            get {
                return ResourceManager.GetString("lbTitleEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre de usuario.
        /// </summary>
        public static string lbTitleEditUsername {
            get {
                return ResourceManager.GetString("lbTitleEditUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificacion de cambio de correo.
        /// </summary>
        public static string lbTitleEmailChangeConfirmation {
            get {
                return ResourceManager.GetString("lbTitleEmailChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una mayúscula .
        /// </summary>
        public static string lbUppercaseLetterRequirement_ {
            get {
                return ResourceManager.GetString("lbUppercaseLetterRequirement ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario .
        /// </summary>
        public static string lbUserName_ {
            get {
                return ResourceManager.GetString("lbUserName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha dejado campos vacios, complete todos .
        /// </summary>
        public static string lbWLogin_ {
            get {
                return ResourceManager.GetString("lbWLogin ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados son incorrectos, intente de nuevo .
        /// </summary>
        public static string lbWLoginWrongData {
            get {
                return ResourceManager.GetString("lbWLoginWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string Login_ {
            get {
                return ResourceManager.GetString("Login ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo? .
        /// </summary>
        public static string NewInGame_ {
            get {
                return ResourceManager.GetString("NewInGame ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password_ {
            get {
                return ResourceManager.GetString("Password ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Register_ {
            get {
                return ResourceManager.GetString("Register ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hunter´s Tropy .
        /// </summary>
        public static string TitleGame_ {
            get {
                return ResourceManager.GetString("TitleGame ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string UserName_ {
            get {
                return ResourceManager.GetString("UserName ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string vtLogin {
            get {
                return ResourceManager.GetString("vtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia .
        /// </summary>
        public static string vtWarningLogin_ {
            get {
                return ResourceManager.GetString("vtWarningLogin ", resourceCulture);
            }
        }
    }
}
