//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trofeoCazador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver amigos.
        /// </summary>
        public static string btnAmigos {
            get {
                return ResourceManager.GetString("btnAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        public static string btnAtras {
            get {
                return ResourceManager.GetString("btnAtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string btnCrearCuenta {
            get {
                return ResourceManager.GetString("btnCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string btnCrearSalaEspera {
            get {
                return ResourceManager.GetString("btnCrearSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string btnEnviar {
            get {
                return ResourceManager.GetString("btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código.
        /// </summary>
        public static string btnEnviarCodigo {
            get {
                return ResourceManager.GetString("btnEnviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar amigo.
        /// </summary>
        public static string btnEnviarInvitacion {
            get {
                return ResourceManager.GetString("btnEnviarInvitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud.
        /// </summary>
        public static string btnEnviarSolicitud {
            get {
                return ResourceManager.GetString("btnEnviarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadisticas.
        /// </summary>
        public static string btnEstadisticas {
            get {
                return ResourceManager.GetString("btnEstadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        public static string btnIniciarPartida {
            get {
                return ResourceManager.GetString("btnIniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string btnInicioSesion {
            get {
                return ResourceManager.GetString("btnInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string btnInvitado {
            get {
                return ResourceManager.GetString("btnInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar amigo.
        /// </summary>
        public static string btnInvitarAmigo {
            get {
                return ResourceManager.GetString("btnInvitarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string btnPerfil {
            get {
                return ResourceManager.GetString("btnPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salas espera.
        /// </summary>
        public static string btnSalasEspera {
            get {
                return ResourceManager.GetString("btnSalasEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar nuevo código.
        /// </summary>
        public static string btnSolicitarNuevoCodigo {
            get {
                return ResourceManager.GetString("btnSolicitarNuevoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver solicitudes amistad.
        /// </summary>
        public static string btnSolicitudes {
            get {
                return ResourceManager.GetString("btnSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string btnUnirseSalaEspera {
            get {
                return ResourceManager.GetString("btnUnirseSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidaste tu contraseña.
        /// </summary>
        public static string contraseñaOlvidada {
            get {
                return ResourceManager.GetString("contraseñaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string inicioSesion {
            get {
                return ResourceManager.GetString("inicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string lbAmigos {
            get {
                return ResourceManager.GetString("lbAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer apellido.
        /// </summary>
        public static string lbApellido {
            get {
                return ResourceManager.GetString("lbApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string lbCambiarContraseña {
            get {
                return ResourceManager.GetString("lbCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por le menos un caracter especial.
        /// </summary>
        public static string lbCaracterEspecialRequisito {
            get {
                return ResourceManager.GetString("lbCaracterEspecialRequisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string lbChat {
            get {
                return ResourceManager.GetString("lbChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string lbCodigo {
            get {
                return ResourceManager.GetString("lbCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código incorrecto, verifica el código o vuelve a generar uno nuevo.
        /// </summary>
        public static string lbCodigoError {
            get {
                return ResourceManager.GetString("lbCodigoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión fallida.
        /// </summary>
        public static string lbConexionFallida {
            get {
                return ResourceManager.GetString("lbConexionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbContraseña {
            get {
                return ResourceManager.GetString("lbContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena actual.
        /// </summary>
        public static string lbContraseñaActual {
            get {
                return ResourceManager.GetString("lbContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvide mi contraseña .
        /// </summary>
        public static string lbContraseniaOlvidada {
            get {
                return ResourceManager.GetString("lbContraseniaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string lbCorreo {
            get {
                return ResourceManager.GetString("lbCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo actual.
        /// </summary>
        public static string lbCorreoActual {
            get {
                return ResourceManager.GetString("lbCorreoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string lbCrearCuenta {
            get {
                return ResourceManager.GetString("lbCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu cuenta.
        /// </summary>
        public static string lbCreaTuCuenta {
            get {
                return ResourceManager.GetString("lbCreaTuCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        public static string lbCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("lbCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta creada exitosamente. Ahora puedes iniciar sesión..
        /// </summary>
        public static string lbCuentaCreada {
            get {
                return ResourceManager.GetString("lbCuentaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdió.
        /// </summary>
        public static string lbDerrota {
            get {
                return ResourceManager.GetString("lbDerrota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El anfitrion salio de la sala de espera. Regresaras al menú principal..
        /// </summary>
        public static string lbDescripcionAnfitrionDejoSalaEsperra {
            get {
                return ResourceManager.GetString("lbDescripcionAnfitrionDejoSalaEsperra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ninguna cuenta asociada a este correo.
        /// </summary>
        public static string lbDescripcionCorreoIncorrecto {
            get {
                return ResourceManager.GetString("lbDescripcionCorreoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este correo ya está registrado. Por favor, elige otro..
        /// </summary>
        public static string lbDescripcionCorreoUsado {
            get {
                return ResourceManager.GetString("lbDescripcionCorreoUsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El inicio de sesión falló o los datos no fueron recuperados correctamente..
        /// </summary>
        public static string lbDescripcionCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("lbDescripcionCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta creada exitosamente.
        /// </summary>
        public static string lbDescripcionCuentaCreada {
            get {
                return ResourceManager.GetString("lbDescripcionCuentaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la base de datos. Porfavor, inténtelo más tarde.
        /// </summary>
        public static string lbDescripcionExcepcionBaseDeDatos {
            get {
                return ResourceManager.GetString("lbDescripcionExcepcionBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Por favor, inténtelo más tarde.
        /// </summary>
        public static string lbDescripcionExcepcionInesperada {
            get {
                return ResourceManager.GetString("lbDescripcionExcepcionInesperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en el servidor. Por favor, inténtelo más tarde.
        /// </summary>
        public static string lbDescripcionExcepcionServidor {
            get {
                return ResourceManager.GetString("lbDescripcionExcepcionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has recibido una invitación de .
        /// </summary>
        public static string lbDescripcionInvitacion {
            get {
                return ResourceManager.GetString("lbDescripcionInvitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has acumulado el máximo de reportes permitidos. Se restringirá tu cuenta por un tiempo establecido..
        /// </summary>
        public static string lbDescripcionJugadorCastigado {
            get {
                return ResourceManager.GetString("lbDescripcionJugadorCastigado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has reportado a este jugador..
        /// </summary>
        public static string lbDescripcionJugadorReportado {
            get {
                return ResourceManager.GetString("lbDescripcionJugadorReportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El anfitrión no puede expulsarse a sí mismo.
        /// </summary>
        public static string lbDescripcionNoExpulsarAnfitrion {
            get {
                return ResourceManager.GetString("lbDescripcionNoExpulsarAnfitrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estas en una sala de espera.
        /// </summary>
        public static string lbDescripcionNoHaySalaEspera {
            get {
                return ResourceManager.GetString("lbDescripcionNoHaySalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este nombre de usuario ya está en uso. Por favor, elige otro.
        /// </summary>
        public static string lbDescripcionNombreUsado {
            get {
                return ResourceManager.GetString("lbDescripcionNombreUsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el código de verificación. Intenta de nuevo..
        /// </summary>
        public static string lbDescripcionProblemasCodigo {
            get {
                return ResourceManager.GetString("lbDescripcionProblemasCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ha sido reportado..
        /// </summary>
        public static string lbDescripcionReporteExitoso {
            get {
                return ResourceManager.GetString("lbDescripcionReporteExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala de espera a la que estas intentando entrar esta llena..
        /// </summary>
        public static string lbDescripcionSalaEsperaLlena {
            get {
                return ResourceManager.GetString("lbDescripcionSalaEsperaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala de espera que estas intentando entrar no existe..
        /// </summary>
        public static string lbDescripcionSalaEsperaNoEncotrada {
            get {
                return ResourceManager.GetString("lbDescripcionSalaEsperaNoEncotrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar con el servidor. Por favor, Inténtelo más tarde..
        /// </summary>
        public static string lbDetallesConexionFallida {
            get {
                return ResourceManager.GetString("lbDetallesConexionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación ha excedido el tiempo de espera. Por favor, inténtelo más tarde..
        /// </summary>
        public static string lbDetallesExcepcionTimeOut {
            get {
                return ResourceManager.GetString("lbDetallesExcepcionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido expulsado de la sala de espera.
        /// </summary>
        public static string lbDetallesExpulsion {
            get {
                return ResourceManager.GetString("lbDetallesExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string lbDiaDeNacimiento {
            get {
                return ResourceManager.GetString("lbDiaDeNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre de usuario.
        /// </summary>
        public static string lbEditarNombreUsuario {
            get {
                return ResourceManager.GetString("lbEditarNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar invitacion.
        /// </summary>
        public static string lbEnviarInvitacion {
            get {
                return ResourceManager.GetString("lbEnviarInvitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Usuario no válido o solicitud ya enviada.
        /// </summary>
        public static string lbErrorNombreDeUsuarioSolicitudAmistad {
            get {
                return ResourceManager.GetString("lbErrorNombreDeUsuarioSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestor amigos.
        /// </summary>
        public static string lbGestorAmigos {
            get {
                return ResourceManager.GetString("lbGestorAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código que se le envio a su correo.
        /// </summary>
        public static string lbIngresarCodigoVerificación {
            get {
                return ResourceManager.GetString("lbIngresarCodigoVerificación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa los siguientes datos.
        /// </summary>
        public static string lbIngresarInformacion {
            get {
                return ResourceManager.GetString("lbIngresarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string lbInicioSesion {
            get {
                return ResourceManager.GetString("lbInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de amistad fue envíada a.
        /// </summary>
        public static string lbInvitacionEnviada {
            get {
                return ResourceManager.GetString("lbInvitacionEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado .
        /// </summary>
        public static string lbInvitado {
            get {
                return ResourceManager.GetString("lbInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar amigos.
        /// </summary>
        public static string lbInvitarAmigos {
            get {
                return ResourceManager.GetString("lbInvitarAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió la invitación a.
        /// </summary>
        public static string lbInvitarAmigoSala {
            get {
                return ResourceManager.GetString("lbInvitarAmigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores en sala espera.
        /// </summary>
        public static string lbJugadoresEnSalaEspera {
            get {
                return ResourceManager.GetString("lbJugadoresEnSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes llenar los campos obligatorios..
        /// </summary>
        public static string lbLlenarCamposObligatorios {
            get {
                return ResourceManager.GetString("lbLlenarCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llenar campos.
        /// </summary>
        public static string lbLlenarCamposObligatorios1 {
            get {
                return ResourceManager.GetString("lbLlenarCamposObligatorios1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo correo.
        /// </summary>
        public static string lbNewEmail {
            get {
                return ResourceManager.GetString("lbNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo apellido.
        /// </summary>
        public static string lbNewLastName {
            get {
                return ResourceManager.GetString("lbNewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lbNombre {
            get {
                return ResourceManager.GetString("lbNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre actual.
        /// </summary>
        public static string lbNombreActual {
            get {
                return ResourceManager.GetString("lbNombreActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lbNombreUsuario {
            get {
                return ResourceManager.GetString("lbNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario actual.
        /// </summary>
        public static string lbnombreUsuarioActual {
            get {
                return ResourceManager.GetString("lbnombreUsuarioActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas con la sala de espera.
        /// </summary>
        public static string lbNoSalaEspera {
            get {
                return ResourceManager.GetString("lbNoSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado una sala.
        /// </summary>
        public static string lbNotificarSalaEsperaCreada {
            get {
                return ResourceManager.GetString("lbNotificarSalaEsperaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contrasena.
        /// </summary>
        public static string lbNuevaContraseña {
            get {
                return ResourceManager.GetString("lbNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo apellido.
        /// </summary>
        public static string lbNuevoApellido {
            get {
                return ResourceManager.GetString("lbNuevoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo correo.
        /// </summary>
        public static string lbNuevoCorreo {
            get {
                return ResourceManager.GetString("lbNuevoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo en el juego?.
        /// </summary>
        public static string lbNuevoEnjuego {
            get {
                return ResourceManager.GetString("lbNuevoEnjuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre.
        /// </summary>
        public static string lbNuevoNombre {
            get {
                return ResourceManager.GetString("lbNuevoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre de usuario.
        /// </summary>
        public static string lbNuevoNombreUsuario {
            get {
                return ResourceManager.GetString("lbNuevoNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener.
        /// </summary>
        public static string lbPoliticaContraseña {
            get {
                return ResourceManager.GetString("lbPoliticaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos 12 caracteres.
        /// </summary>
        public static string lbPorLoMenos12Caracteres {
            get {
                return ResourceManager.GetString("lbPorLoMenos12Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una mayuscula.
        /// </summary>
        public static string lbPorLoMenosUnaMayuscula {
            get {
                return ResourceManager.GetString("lbPorLoMenosUnaMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una minuscula.
        /// </summary>
        public static string lbPorLoMenosUnaMinuscula {
            get {
                return ResourceManager.GetString("lbPorLoMenosUnaMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un numero.
        /// </summary>
        public static string lbPorLoMenosUnNumero {
            get {
                return ResourceManager.GetString("lbPorLoMenosUnNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible enviar la solicitud de amistad, inténtelo de nuevo.
        /// </summary>
        public static string lbProblemasInvitacion {
            get {
                return ResourceManager.GetString("lbProblemasInvitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse .
        /// </summary>
        public static string lbRegistrarse {
            get {
                return ResourceManager.GetString("lbRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una minúscula .
        /// </summary>
        public static string lbRequerimientoMinuscula {
            get {
                return ResourceManager.GetString("lbRequerimientoMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera creada con el código:.
        /// </summary>
        public static string lbSalaEsperaCreada {
            get {
                return ResourceManager.GetString("lbSalaEsperaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala de espera no existe.
        /// </summary>
        public static string lbSalaEsperaInexistente {
            get {
                return ResourceManager.GetString("lbSalaEsperaInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala de espera esta llena.
        /// </summary>
        public static string lbSalaEsperaLlena {
            get {
                return ResourceManager.GetString("lbSalaEsperaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo apellido.
        /// </summary>
        public static string lbSegundoApellido {
            get {
                return ResourceManager.GetString("lbSegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un amigo para invitar..
        /// </summary>
        public static string lbSeleccionaAmigo {
            get {
                return ResourceManager.GetString("lbSeleccionaAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una imagen de perfil:.
        /// </summary>
        public static string lbSeleccionarFoto {
            get {
                return ResourceManager.GetString("lbSeleccionarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de Amistad.
        /// </summary>
        public static string lbSolicitudesAmistad {
            get {
                return ResourceManager.GetString("lbSolicitudesAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un caracter especial.
        /// </summary>
        public static string lbSpecialCharacterRequirement_ {
            get {
                return ResourceManager.GetString("lbSpecialCharacterRequirement ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar correo.
        /// </summary>
        public static string lbTitleChangeEmail {
            get {
                return ResourceManager.GetString("lbTitleChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre.
        /// </summary>
        public static string lbTitleEditName {
            get {
                return ResourceManager.GetString("lbTitleEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion editar correo.
        /// </summary>
        public static string lbTitleEmailChangeConfirmation {
            get {
                return ResourceManager.GetString("lbTitleEmailChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala espera eliminada.
        /// </summary>
        public static string lbTituloAnfitrionSalioSalaEspera {
            get {
                return ResourceManager.GetString("lbTituloAnfitrionSalioSalaEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar correo.
        /// </summary>
        public static string lbTituloCambiarCorreo {
            get {
                return ResourceManager.GetString("lbTituloCambiarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas con correo.
        /// </summary>
        public static string lbTituloCorreoEligido {
            get {
                return ResourceManager.GetString("lbTituloCorreoEligido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups tenemos problemas.
        /// </summary>
        public static string lbTituloCorreoNoReconocido {
            get {
                return ResourceManager.GetString("lbTituloCorreoNoReconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre.
        /// </summary>
        public static string lbTituloEditarNombre {
            get {
                return ResourceManager.GetString("lbTituloEditarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores en la validación.
        /// </summary>
        public static string lbTituloErroresValidacion {
            get {
                return ResourceManager.GetString("lbTituloErroresValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de la base de datos.
        /// </summary>
        public static string lbTituloExcepcionBaseDeDatos {
            get {
                return ResourceManager.GetString("lbTituloExcepcionBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado.
        /// </summary>
        public static string lbTituloExcepcionInesperada {
            get {
                return ResourceManager.GetString("lbTituloExcepcionInesperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el servidor.
        /// </summary>
        public static string lbTituloExcepcionServidor {
            get {
                return ResourceManager.GetString("lbTituloExcepcionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera excedido.
        /// </summary>
        public static string lbTituloExcepcionTimeOut {
            get {
                return ResourceManager.GetString("lbTituloExcepcionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exito.
        /// </summary>
        public static string lbTituloExito {
            get {
                return ResourceManager.GetString("lbTituloExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsado.
        /// </summary>
        public static string lbTituloExpulsion {
            get {
                return ResourceManager.GetString("lbTituloExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola parece que.
        /// </summary>
        public static string lbTituloGenerico {
            get {
                return ResourceManager.GetString("lbTituloGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación.
        /// </summary>
        public static string lbTituloInvitacionAmigo {
            get {
                return ResourceManager.GetString("lbTituloInvitacionAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada.
        /// </summary>
        public static string lbTituloInvitacionEnviada {
            get {
                return ResourceManager.GetString("lbTituloInvitacionEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hunter´s Tropy .
        /// </summary>
        public static string lbTituloJuego {
            get {
                return ResourceManager.GetString("lbTituloJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido baneado.
        /// </summary>
        public static string lbTituloJugadorCastigado {
            get {
                return ResourceManager.GetString("lbTituloJugadorCastigado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador ya reportado.
        /// </summary>
        public static string lbTituloJugadorReportado {
            get {
                return ResourceManager.GetString("lbTituloJugadorReportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte exitoso.
        /// </summary>
        public static string lbTituloReporteExitoso {
            get {
                return ResourceManager.GetString("lbTituloReporteExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala espera llena.
        /// </summary>
        public static string lbTituloSalaEsperaLlena {
            get {
                return ResourceManager.GetString("lbTituloSalaEsperaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala espera no encotrada.
        /// </summary>
        public static string lbTituloSalaEsperaNoEncotrada {
            get {
                return ResourceManager.GetString("lbTituloSalaEsperaNoEncotrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad.
        /// </summary>
        public static string lbTituloSolicitudAmistad {
            get {
                return ResourceManager.GetString("lbTituloSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups.
        /// </summary>
        public static string lbTituloUps {
            get {
                return ResourceManager.GetString("lbTituloUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una mayúscula .
        /// </summary>
        public static string lbUppercaseLetterRequirement_ {
            get {
                return ResourceManager.GetString("lbUppercaseLetterRequirement ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lbUsuario {
            get {
                return ResourceManager.GetString("lbUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario en línea.
        /// </summary>
        public static string lbUsuarioLinea {
            get {
                return ResourceManager.GetString("lbUsuarioLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta cuenta ya ha iniciado sesión desde otro dispositivo.
        /// </summary>
        public static string lbUsuarioYaEstaEnLinea {
            get {
                return ResourceManager.GetString("lbUsuarioYaEstaEnLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar codigo.
        /// </summary>
        public static string lbValidarCodigo {
            get {
                return ResourceManager.GetString("lbValidarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificacion de cambio de correo.
        /// </summary>
        public static string lbVerificacionCambioCorreo {
            get {
                return ResourceManager.GetString("lbVerificacionCambioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Win.
        /// </summary>
        public static string lbVictoria {
            get {
                return ResourceManager.GetString("lbVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string nombreUsuario_ {
            get {
                return ResourceManager.GetString("nombreUsuario ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string tbCambiarContraseña {
            get {
                return ResourceManager.GetString("tbCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar correo.
        /// </summary>
        public static string tbCambiarCorreo {
            get {
                return ResourceManager.GetString("tbCambiarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string tbContraseña {
            get {
                return ResourceManager.GetString("tbContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo es.
        /// </summary>
        public static string tbCopiaCodigo {
            get {
                return ResourceManager.GetString("tbCopiaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string tbCorreo {
            get {
                return ResourceManager.GetString("tbCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion cambio correo.
        /// </summary>
        public static string tbCorreoCodigoConfirmacion {
            get {
                return ResourceManager.GetString("tbCorreoCodigoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string tbCuenta {
            get {
                return ResourceManager.GetString("tbCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de verificación que recibiste por correo.
        /// </summary>
        public static string tbDescripcionCodigo {
            get {
                return ResourceManager.GetString("tbDescripcionCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su correo para recuperar su contraseña.
        /// </summary>
        public static string tbDescripcionRecuperarContraseña {
            get {
                return ResourceManager.GetString("tbDescripcionRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar nombre usuario.
        /// </summary>
        public static string tbEditarNombreUsuario {
            get {
                return ResourceManager.GetString("tbEditarNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amiguito@gmail.com.
        /// </summary>
        public static string tbEjemploCorreo {
            get {
                return ResourceManager.GetString("tbEjemploCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Solicitud de Amistad.
        /// </summary>
        public static string tbEnviarSolicitud {
            get {
                return ResourceManager.GetString("tbEnviarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto perfil.
        /// </summary>
        public static string tbFotoPerfil {
            get {
                return ResourceManager.GetString("tbFotoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el correo.
        /// </summary>
        public static string tbIngresaCorreo {
            get {
                return ResourceManager.GetString("tbIngresaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar por correo.
        /// </summary>
        public static string tbInvitarPorCorreo {
            get {
                return ResourceManager.GetString("tbInvitarPorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        public static string tbMenuPrincipal {
            get {
                return ResourceManager.GetString("tbMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario.
        /// </summary>
        public static string tbNombreUsuario {
            get {
                return ResourceManager.GetString("tbNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario actual.
        /// </summary>
        public static string tbNombreUsuarioActual {
            get {
                return ResourceManager.GetString("tbNombreUsuarioActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre usuario.
        /// </summary>
        public static string tbNuevoNombreUsuario {
            get {
                return ResourceManager.GetString("tbNuevoNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string tituloRecuperarContraseña {
            get {
                return ResourceManager.GetString("tituloRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión .
        /// </summary>
        public static string vtInicioSesion {
            get {
                return ResourceManager.GetString("vtInicioSesion", resourceCulture);
            }
        }
    }
}
