//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trofeoCazador.ServicioDelJuego {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorDataContract", Namespace="http://schemas.datacontract.org/2004/07/ServicioJuego")]
    [System.SerializableAttribute()]
    public partial class JugadorDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroFotoPerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroFotoPerfil {
            get {
                return this.NumeroFotoPerfilField;
            }
            set {
                if ((this.NumeroFotoPerfilField.Equals(value) != true)) {
                    this.NumeroFotoPerfilField = value;
                    this.RaisePropertyChanged("NumeroFotoPerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaDataContract", Namespace="http://schemas.datacontract.org/2004/07/ServicioJuego")]
    [System.SerializableAttribute()]
    public partial class CuentaDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaHash {
            get {
                return this.ContraseniaHashField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaHashField, value) != true)) {
                    this.ContraseniaHashField = value;
                    this.RaisePropertyChanged("ContraseniaHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDelJuego.IGestionCuentaServicio")]
    public interface IGestionCuentaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuentaServicio/GetData", ReplyAction="http://tempuri.org/IGestionCuentaServicio/GetDataResponse")]
        bool GetData(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuentaServicio/GetData", ReplyAction="http://tempuri.org/IGestionCuentaServicio/GetDataResponse")]
        System.Threading.Tasks.Task<bool> GetDataAsync(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuentaServicio/AgregarJugador", ReplyAction="http://tempuri.org/IGestionCuentaServicio/AgregarJugadorResponse")]
        bool AgregarJugador(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuentaServicio/AgregarJugador", ReplyAction="http://tempuri.org/IGestionCuentaServicio/AgregarJugadorResponse")]
        System.Threading.Tasks.Task<bool> AgregarJugadorAsync(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCuentaServicioChannel : trofeoCazador.ServicioDelJuego.IGestionCuentaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCuentaServicioClient : System.ServiceModel.ClientBase<trofeoCazador.ServicioDelJuego.IGestionCuentaServicio>, trofeoCazador.ServicioDelJuego.IGestionCuentaServicio {
        
        public GestionCuentaServicioClient() {
        }
        
        public GestionCuentaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCuentaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetData(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuent) {
            return base.Channel.GetData(jugador, cuent);
        }
        
        public System.Threading.Tasks.Task<bool> GetDataAsync(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuent) {
            return base.Channel.GetDataAsync(jugador, cuent);
        }
        
        public bool AgregarJugador(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuenta) {
            return base.Channel.AgregarJugador(jugador, cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarJugadorAsync(trofeoCazador.ServicioDelJuego.JugadorDataContract jugador, trofeoCazador.ServicioDelJuego.CuentaDataContract cuenta) {
            return base.Channel.AgregarJugadorAsync(jugador, cuenta);
        }
    }
}
